# Generated by Django 3.1 on 2020-08-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
